version: '3.6'

services:
  db:
    image: mysql:8.0.27
    container_name: db_${PROJECT}  ## Custom container name corresponding to project. Configure in .env file
    environment:
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_ROOT_USER=${MYSQL_ROOT_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    expose:
      - "3306"
    volumes:
      - ../mlflow_sql_db/data:/var/lib/mysql  ## custom folder
    restart: always

  s3:
    image: minio/minio:RELEASE.2021-11-09T03-21-45Z
    container_name: s3_${PROJECT}
    environment:
      - MINIO_ACCESS_KEY=${AWS_ACCESS_KEY_ID}
      - MINIO_SECRET_KEY=${AWS_SECRET_ACCESS_KEY}
    expose:
      - "9000"
    ports:
      - "${S3_PORT}:9000"   ## Mapping container's 9000 port to the host machine's S3_PORT. Configure in .env file
    command: server /artifactstore
    volumes:
      - ../minio:/artifactstore
    restart: always

  mc:
    image: minio/mc:RELEASE.2021-11-05T10-05-06Z
    depends_on:
    - s3
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host rm local;
      until(/usr/bin/mc config host add local http://s3:9000 ${AWS_ACCESS_KEY_ID} ${AWS_SECRET_ACCESS_KEY}) do echo '...waiting...' && sleep 1; done;
      /usr/bin/mc mb --quiet local/artifactstore/;
      /usr/bin/mc policy set public local/artifactstore;
      "

  web: ## mlflow server
    build:
      context: ./mlflow_server
      args:
        - PROXY_SERVER=${PROXY_SERVER}
    image: mlflow_server
    environment:
      - MLFLOW_S3_ENDPOINT_URL=http://s3:9000
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    container_name: mlflow_${PROJECT}
    depends_on:
      - "db"
      - "s3"
      - "mc"
    expose:
      - "5000"
    command: mlflow server --backend-store-uri mysql+pymysql://${MYSQL_USER}:${MYSQL_PASSWORD}@db:3306/${MYSQL_DATABASE} --default-artifact-root s3://artifactstore --host 0.0.0.0

  nginx:
    restart: always
    build:
      context: ./nginx
      args:
        - USERNAME=${MLFLOW_USER}
        - PASSWD=${MLFLOW_PASSWORD}
    image: mlflow_nginx
    container_name: mlflow_nginx_${PROJECT}
    ports:
      - "${PORT}:80"
    depends_on:
      - web